version: "3.8"

services:
  app:
    image: yoyobara/fullstack-todo-list-application-app:latest
    container_name: todo-list-app
    restart: always
    ports:
      - "8000:8000"
    environment:
      ENVIRONMENT: production
      DEPLOYMENT: other
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: todo_list
      PORT: 8000
      HOST: "0.0.0.0"
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: todo-list-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_list
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
