version: "3.8"

services:
  app:
    image: yoyobara/fullstack-todo-list-application-app:latest
    container_name: todo-list-app
    restart: always
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      HOST: "0.0.0.0"
